# Generated by Django 5.2.5 on 2025-08-12 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Nome', max_length=100)),
                ('sobrenome', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Sobrenome', max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Telefone', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=150, null=True)),
                ('cnpj_cpf', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CNPJ_CPF', max_length=20, null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='Ativo', null=True)),
                ('data_entrada', models.DateField(blank=True, db_column='DataEntrada', null=True)),
                ('data_saida', models.DateField(blank=True, db_column='DataSaida', null=True)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('endereco', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Endereco', max_length=255)),
                ('ativo', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Ativo', max_length=50)),
                ('expira_em', models.DateField(db_column='ExpiraEm')),
                ('donoid', models.ForeignKey(db_column='DonoId', on_delete=django.db.models.deletion.DO_NOTHING, to='app.cliente')),
            ],
            options={
                'db_table': 'Dominio',
            },
        ),
    ]
