# Generated by Django 5.2.5 on 2025-08-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dominio',
            name='hospedado_em',
            field=models.ForeignKey(blank=True, db_column='HospedadoEm', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hospedagem'),
        ),
    ]
